<?php return array(
    'root' => array(
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => NULL,
        'name' => '__root__',
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'enyo/dropzone' => array(
            'pretty_version' => 'v5.9.3',
            'version' => '5.9.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../enyo/dropzone',
            'aliases' => array(),
            'reference' => '286b2dc1f1195bd12169e4c9d5f91cfbe46e245f',
            'dev_requirement' => false,
        ),
        'uikit/uikit' => array(
            'pretty_version' => 'v3.10.1',
            'version' => '3.10.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../uikit/uikit',
            'aliases' => array(),
            'reference' => '105b3ca57f500d062e75d7b8d0c0195943031e4f',
            'dev_requirement' => false,
        ),
    ),
);
